# -*- coding: utf-8 -*-
"""ResponsibleAIDatasetScript.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uhEfuLbVNoGg1A-n227to9JdYa8qsO3y
"""

import csv
import random

platforms = ["YouTube", "TikTok"]
challenge_titles = [
    "Condom Snorting Challenge",
    "The Fire Challenge",
    "Tide Pod Eating Challenge",
    "Inhaling Cinnamon Challenge",
    "Hot Coil Challenge",
    "Choking Game Challenge",
    "Drinking Boiling Water Challenge",
    "The Deodorant Challenge",
    "Salt and Ice Challenge",
    "The Duct Tape Challenge",
]

def generate_data():
    data = []
    for i in range(1, 15001):
        platform = random.choice(platforms)
        title = random.choice(challenge_titles)
        uploader = f"User{i}"
        view_count = random.randint(10000, 5000000)
        likes = random.randint(1000, 150000)
        dislikes = random.randint(500, 50000)
        hours_played = round(view_count * random.uniform(0.0002, 0.0005), 2)

        data.append(
            [i, platform, f"{title} - {platform}", uploader, view_count, likes, dislikes, hours_played]
        )
    return data

def write_csv(data, filename="dangerous_challenges.csv"):
    with open(filename, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["Video_ID", "Platform", "Title", "Uploader", "View_Count", "Likes", "Dislikes", "Hours_Played"])
        writer.writerows(data)

if __name__ == "__main__":
    data = generate_data()
    write_csv(data)

